title: aut0arch Documentation
description: Automated architecture discovery and explanation pipeline.
theme: just-the-docs

url: https://aut0arch.github.io/docs # Update this if deploying to a different URL

color_scheme: dark

# just-the-docs specific settings
search_enabled: true
heading_anchors: true
